## content of /src/main/resources/application.yml
server:
  port: 9000
  servlet.contextPath: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: nathan
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update